version: "3.8"

services:
  mongodb:
    image: mongo
    env_file:
      - ./env/mongo.env
    volumes:
      - data:/data/db  

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env
    volumes:
      - logs:/app/logs 
      - ./backend:/app
      - /app/node_modules
    ports: 
      - "80:80"  
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports: 
      - "3000:3000"  
    tty: true
    stdin_open: true  
  
volumes:
   data:  
   logs: