name: Docker Image CI

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Docker compose run 
        uses: actions/checkout@v1
      - 
        name: Start containers
        run: docker compose -f "docker-compose.yaml" up -d 
        
